version: "3.8"
networks:
  movie_movie_network:
    external: true
  review_review_network:
    external: true

services:
  app:
    build: ./src
    ports:
      - ${APP_PORT}:5000
    networks:
      - review_review_network
      - movie_movie_network
    environment:
      MOVIE_SERVICE_URI: http://movie_app_1:${MOVIE_SERVICE_PORT}
      REVIEW_SERVICE_URI: http://review_app_1:${REVIEW_SERVICE_PORT}
